name: "Cargo Audit"
author: "simonhyll"
description: "Runs cargo audit fix"
branding:
  color: blue
  icon: aperture
inputs:
  path:
    description: "Path to Cargo.lock"
    required: false
    default: "./"
outputs:
  warnings:
    description: 'false'
  critical:
    description: 'false'
runs:
  using: "docker"
  image: "docker://ghcr.io/simonhyll/cargo-audit:latest"
  args:
    - ${{ inputs.path }}
