name: "Cargo Audit"
author: "simonhyll"
description: "Runs cargo audit fix"
branding:
  color: blue
  icon: aperture
inputs:
  path:
    description: "Path to Cargo.lock"
    required: false
    default: "./" # E.g. "sample", "sub/directory/crate"
  fix:
    description: "Whether or not to run with fix"
    required: false
    default: "true" # true or false
  deny:
    description: "Exit with error on: warnings, unmaintaned, unsound, yanked"
    required: false
    default: "false" # warnings, unmaintained, unsound, yanked
outputs:
  warnings:
    description: "false" # Whether or not there were warnings
runs:
  using: "docker"
  image: "docker://ghcr.io/simonhyll/cargo-audit:latest"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.fix }}
    - ${{ inputs.deny }}
