name: Test action
on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/cargo@v1
      - name: Run cargo audit fix
        id: hello
        uses: simonhyll/cargo-audit@v0.1.1
