name: Test action
on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      
      - name: Run cargo audit fix
        uses: simonhyll/cargo-audit@v0.1.2
