name: Test action
on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo audit fix
        uses: simonhyll/cargo-audit@v0.1.1
